#!/usr/bin/perl

use warnings;
use strict;
use Archive::Tar;

my $fh;

# Store uniprot sequences into hash
my %fasta = ();
my $seq = "";
my $header = "";
my $tar = Archive::Tar -> new();
#$tar->read("../proteinSeq/uniprot/uniprot_sprot.fasta.tar.gz");
$tar->read("../proteinSeq/uniprot/uniprot_all_ath.fasta.tar.gz");
foreach my $file ($tar -> list_files) {
    my @data = split("\n", $tar -> get_content($file));
    foreach my $line (@data) {
	if ($line =~ /^>/) {
	    $fasta{$header} = $seq if ($seq);
	    $header = (split("\\|", $line))[1];
	    $seq = "";
	}         
	else {    
	    $line =~ s/\s+//g;
	    $seq .= $line;
	}
    }
    if ($seq) { # handle last sequence
	$fasta{$header} = $seq;
    }    
}

my @fn = ("ss_candidates.tsv", "proteome.tsv");
for (my $i = 0; $i < scalar(@fn); $i++) {
    open($fh, $fn[$i]) or die(sprintf("[ERROR] Could not find file %s\n", $fn[$i]));
    my $fnOut = $fn[$i];
    $fnOut =~ s/tsv/fa/g;
    open(my $fhOut, ">", $fnOut);
    while (my $line = <$fh>) {
	chomp($line);
	if ($line !~ /Majority/) {
	    my @arr = split("\t", $line);
	    my @ids = split(";", $arr[2]);
	    for (my $j=0; $j < scalar(@ids); $j++) {
		if (exists($fasta{$ids[$j]})) {
		    printf($fhOut ">%s\n", $ids[$j]);
		    printf($fhOut "%s\n", $fasta{$ids[$j]});
		    last;
		}
		if ($j == scalar(@ids) - 1) {
		    printf("[WARNING] In %s: No entry found for %s\n", $fn[$i], join(";", @ids));
		}
	    }
	}
    }
    close($fh);
    close($fhOut);
}

