#!/bin/bash

fasta-get-markov -protein ../../interactome/ss_candidates.fa > background.txt
meme -oc . -protein -minw 3 -maxw 30 -evt 0.1 -nmotifs 100 -bfile background.txt ../../interactome/ss_candidates.fa 
