#!/usr/bin/perl

use warnings;
use strict;

my %ht = ();
while (my $line = <>) {
    chomp($line);
    my @arr = split("\t", $line);
    if ($arr[2] eq "gene") {
	(my $geneName) = $line =~ /Name=(\w+)/;
	(my $bioType) = $line =~ /Note=(\w+);/;
	my $entry = [$bioType, $arr[0], $arr[3], $arr[4], $arr[6]];
	$ht{$geneName} = $entry;
    }
}

foreach my $key (sort keys %ht) {
    printf("%s\t%s\n", $key, join("\t", @{$ht{$key}}));
}
